spring:
  sharding-sphere:
    datasource:
      names: db1
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.98.149.207:3306/test?characterEncoding=UTF-8&useSSL=false
        username: root
        password: 158d3e483dc2
        # 数据源其他配置
        druid:
          # 连接池初始化时创建的连接数
          initialSize: 5
          # 连接池中保持的最小空闲连接数
          minIdle: 5
          # 连接池中允许的最大活动连接数
          maxActive: 20
          # 获取连接时的最大等待时间，超过此时间将抛出异常
          maxWait: 60000
          # 两次检查连接的时间间隔
          timeBetweenEvictionRunsMillis: 60000
          # 连接最小空闲时间，超过这个时间的连接将被回收
          minEvictableIdleTimeMillis: 300000
          # 是否自动回收超时连接
          remove-abandoned: true
          # 自动回收超时连接的等待时间
          remove-abandoned-timeout-millis: 1800
    sharding:
      tables:
        # 逻辑表 对应数据库中 0 1 2 3
        order_detail:
          actual-data-nodes: db1.order_detail_$->{0..3}
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: order_detail_$->{order_id % 4}
        orders:
          actual-data-nodes: db1.orders_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: orders_$->{id % 2}
    # sharding-jdbc日志打印
    props:
      sql:
        show: true