server:
  port: 1009

spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组，默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: true
      druid:
        initial-size: 4
        min-idle: 4
        max-active: 50
        max-wait: 600000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位：毫秒
        min-evictable-idle-time-millis: 300000
        # 配置一个连接在池中最大生存的时间，单位：毫秒
        max-evictable-idle-time-millis: 900000
        # 配置检测连接是否有效
        validation-query: SELECT 1


#
#    url: jdbc:mysql://47.98.149.207:3307/test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 158d3e483dc2
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true

customer:
  tenantConfigSet:
    - tenantId: 1
      jdbcUrl: jdbc:mysql://47.98.149.207:3307/test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      jdbcUserName: root
      jdbcPassword: 158d3e483dc2
    - tenantId: 2
      jdbcUrl: jdbc:mysql://47.98.149.207:3308/test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      jdbcUserName: root
      jdbcPassword: 158d3e483dc2
