server:
  port: 1001

spring:
  datasource:
    url: jdbc:mysql://47.98.149.207:3306/flowable?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 158d3e483dc2
    driver-class-name: com.mysql.cj.jdbc.Driver

flowable:
  idm:
    app:
      admin:
        password: test
        user-id: admin
        first-name: admin
        last-name: admin
